config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :cctvs
  resources :customers
  root to: 'home#index'
  devise_for :users

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cctv.rb
class Cctv < ApplicationRecord
  belongs_to :product
  has_many :items
end

app/controllers/cctvs_controller.rb
class CctvsController < ApplicationController
  before_action :set_cctv, only: [:show, :edit, :update, :destroy]

  # GET /cctvs
  # GET /cctvs.json
  def index
    @cctvs = Cctv.all
  end

  # GET /cctvs/1
  # GET /cctvs/1.json
  def show
  end

  # GET /cctvs/new
  def new
    @cctv = Cctv.new

  end

  # GET /cctvs/1/edit
  def edit
  end

  # POST /cctvs
  # POST /cctvs.json
  def create
    @cctv = Cctv.new(cctv_params)

    respond_to do |format|
      if @cctv.save
        format.html { redirect_to @cctv, notice: 'Cctv was successfully created.' }
        format.json { render :show, status: :created, location: @cctv }
      else
        format.html { render :new }
        format.json { render json: @cctv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cctvs/1
  # PATCH/PUT /cctvs/1.json
  def update
    respond_to do |format|
      if @cctv.update(cctv_params)
        format.html { redirect_to @cctv, notice: 'Cctv was successfully updated.' }
        format.json { render :show, status: :ok, location: @cctv }
      else
        format.html { render :edit }
        format.json { render json: @cctv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cctvs/1
  # DELETE /cctvs/1.json
  def destroy
    @cctv.destroy
    respond_to do |format|
      format.html { redirect_to cctvs_url, notice: 'Cctv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cctv
      @cctv = Cctv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cctv_params
      params.require(:cctv).permit(:item_name, :category, :price)
    end
end

app/helpers/cctvs_helper.rb
module CctvsHelper
end

app/views/cctvs/_form.html.erb
<%= simple_form_for(@cctv) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">


    <%= f.input :category %>
    <%= f.collection_select :product_id, Product.all, :id, :name, {include_blank: "Select Category", label: false},{:class=>'form-control', :autofocus => true} %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cctvs/edit.html.erb
<h1>Editing Cctv</h1>

<%= render 'form', cctv: @cctv %>

<%= link_to 'Show', @cctv %> |
<%= link_to 'Back', cctvs_path %>

app/views/cctvs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cctvs</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Category</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cctvs.each do |cctv| %>
      <tr>
        <td><%= cctv.item_name %></td>
        <td><%= cctv.category %></td>
        <td><%= cctv.price %></td>
        <td><%= link_to 'Show', cctv %></td>
        <td><%= link_to 'Edit', edit_cctv_path(cctv) %></td>
        <td><%= link_to 'Destroy', cctv, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cctv', new_cctv_path %>

app/views/cctvs/new.html.erb
<h1>New Cctv</h1>

<%= render 'form', cctv: @cctv %>

<%= link_to 'Back', cctvs_path %>

app/views/cctvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @cctv.item_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @cctv.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cctv.price %>
</p>




<%= link_to 'Edit', edit_cctv_path(@cctv) %> |
<%= link_to 'Back', cctvs_path %>